/**
 * Custom Provider
 * 
 * Generic custom API implementation for self-hosted or other compatible LLM APIs.
 * Supports OpenAI-compatible endpoints and custom configurations.
 * 
 * @author Agentic Content Flow Team
 * @version 2.0.0
 * @since 2025-06-17
 */

import { 
  LLMAPIConfig, 
  LLMRequest, 
  LLMResponse, 
  GenerationType 
} from '../../generatortypes';
import { LLMProviderInterface } from '../factory/LLMProviderFactory';
import { extractCodeFromMarkdown, createLegacyMetadata } from '../utils/providerUtils';

export class CustomProvider implements LLMProviderInterface {
  async generateContent(request: LLMRequest): Promise<LLMResponse> {
    const config = request.config;
    if (!config?.baseUrl || !config?.model) {
      throw new Error('Custom provider requires baseUrl and model');
    }

    const response = await fetch(`${config.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${config.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: config.model,
        messages: [
          {
            role: 'system',
            content: this.getSystemPrompt(request.type)
          },
          {
            role: 'user',
            content: request.prompt
          }
        ],
        max_tokens: config.maxTokens || 2048,
        temperature: config.temperature || 0.3,
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Custom API error: ${response.status} ${error}`);
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || data.response || '';
    
    if (!content) {
      throw new Error('No content generated by custom provider');
    }

    // Extract code from markdown if present (legacy compatibility)
    const extractedContent = extractCodeFromMarkdown(content);
    const legacyMetadata = createLegacyMetadata('custom provider');

    return {
      content: extractedContent,
      provider: 'custom',
      model: config.model,
      confidence: 0.75, // Default confidence for custom providers
      usage: {
        promptTokens: data.usage?.prompt_tokens || 0,
        completionTokens: data.usage?.completion_tokens || 0,
        totalTokens: data.usage?.total_tokens || 0
      },
      timestamp: new Date().toISOString(),
      metadata: {
        endpoint: config.baseUrl,
        customModel: config.model,
        // Legacy compatibility fields
        ...legacyMetadata
      }
    };
  }

  async testConnection(config: LLMAPIConfig): Promise<{ success: boolean; error?: string }> {
    if (!config.baseUrl) {
      return { success: false, error: 'Base URL is required for custom provider' };
    }

    try {
      // Try to access models endpoint first
      const response = await fetch(`${config.baseUrl}/models`, {
        headers: {
          'Authorization': `Bearer ${config.apiKey}`,
        },
      });

      if (response.ok) {
        return { success: true };
      } else {
        const error = await response.text();
        return { success: false, error: `HTTP ${response.status}: ${error}` };
      }
    } catch (error) {
      return { success: false, error: error instanceof Error ? error.message : 'Connection failed' };
    }
  }

  getProviderInfo() {
    return {
      name: 'Custom Provider',
      models: ['custom-model'],
      defaultModel: 'custom-model'
    };
  }

  getUsageEstimate(request: LLMRequest): { estimatedTokens: number; estimatedCost: number } {
    const estimatedTokens = Math.ceil(request.prompt.length / 4) + 500;
    return { estimatedTokens, estimatedCost: 0 }; // Unknown cost for custom providers
  }

  private getSystemPrompt(type: GenerationType): string {
    const basePrompt = 'You are an expert code generator for the Agentic Content Flow system.';
    
    switch (type) {
      case 'process':
        return `${basePrompt} Generate JavaScript process functions that are secure, efficient, and well-documented.`;
      case 'flow':
        return `${basePrompt} Generate complete flow structures with nodes and edges that create meaningful data processing pipelines.`;
      default:
        return basePrompt;
    }
  }
}