/**
 * Google Gemini Provider
 * 
 * Google Gemini API implementation for LLM content generation.
 * Supports Gemini Pro and Gemini Pro Vision models.
 * 
 * @author Agentic Content Flow Team
 * @version 2.0.0
 * @since 2025-06-17
 */

import { 
  LLMAPIConfig, 
  LLMRequest, 
  LLMResponse, 
  GenerationType 
} from '../../generatortypes';
import { LLMProviderInterface } from '../factory/LLMProviderFactory';
import { extractCodeFromMarkdown, createLegacyMetadata } from '../utils/providerUtils';

export class GeminiProvider implements LLMProviderInterface {
  private readonly baseUrl = 'https://generativelanguage.googleapis.com/v1beta';

  async generateContent(request: LLMRequest): Promise<LLMResponse> {
    const config = request.config;
    if (!config?.apiKey) {
      throw new Error('Gemini API key is required');
    }

    const model = config.model || 'gemini-pro';

    const response = await fetch(`${this.baseUrl}/models/${model}:generateContent?key=${config.apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: `${this.getSystemPrompt(request.type)}\n\n${request.prompt}`
          }]
        }],
        generationConfig: {
          maxOutputTokens: config.maxTokens || 2048,
          temperature: config.temperature || 0.3,
        }
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Gemini API error: ${response.status} ${error}`);
    }

    const data = await response.json();
    const candidate = data.candidates?.[0];
    const content = candidate?.content?.parts?.[0]?.text || '';
    
    if (!content) {
      throw new Error('No content generated by Gemini');
    }

    // Extract code from markdown if present (legacy compatibility)
    const extractedContent = extractCodeFromMarkdown(content);
    const legacyMetadata = createLegacyMetadata('Google Gemini');

    return {
      content: extractedContent,
      provider: 'gemini',
      model,
      confidence: this.calculateConfidence(candidate),
      usage: {
        promptTokens: 0, // Gemini doesn't provide token usage in response
        completionTokens: 0,
        totalTokens: 0
      },
      timestamp: new Date().toISOString(),
      metadata: {
        finishReason: candidate?.finishReason,
        safetyRatings: candidate?.safetyRatings,
        // Legacy compatibility fields
        ...legacyMetadata
      }
    };
  }

  async testConnection(config: LLMAPIConfig): Promise<{ success: boolean; error?: string }> {
    if (!config.apiKey) {
      return { success: false, error: 'API key is required' };
    }

    try {
      const response = await fetch(`${this.baseUrl}/models?key=${config.apiKey}`);

      if (response.ok) {
        return { success: true };
      } else {
        const error = await response.text();
        return { success: false, error: `HTTP ${response.status}: ${error}` };
      }
    } catch (error) {
      return { success: false, error: error instanceof Error ? error.message : 'Connection failed' };
    }
  }

  getProviderInfo() {
    return {
      name: 'Google Gemini',
      models: ['gemini-pro', 'gemini-pro-vision'],
      defaultModel: 'gemini-pro'
    };
  }

  getUsageEstimate(request: LLMRequest): { estimatedTokens: number; estimatedCost: number } {
    const estimatedTokens = Math.ceil(request.prompt.length / 4) + 500;
    const costPerToken = 0.000002; // Rough estimate for Gemini Pro
    return { estimatedTokens, estimatedCost: estimatedTokens * costPerToken };
  }

  private getSystemPrompt(type: GenerationType): string {
    const basePrompt = 'You are an expert code generator for the Agentic Content Flow system.';
    
    switch (type) {
      case 'process':
        return `${basePrompt} Generate JavaScript process functions that are secure, efficient, and well-documented.`;
      case 'flow':
        return `${basePrompt} Generate complete flow structures with nodes and edges that create meaningful data processing pipelines.`;
      default:
        return basePrompt;
    }
  }

  private calculateConfidence(candidate: any): number {
    // Calculate confidence based on finish reason and safety ratings
    if (candidate?.finishReason === 'STOP') return 0.8;
    if (candidate?.finishReason === 'MAX_TOKENS') return 0.6;
    return 0.5;
  }
}