/**
 * Anthropic Claude Provider
 * 
 * Anthropic Claude API implementation for LLM content generation.
 * Supports Claude 3 family models (Opus, Sonnet, Haiku).
 * 
 * @author Agentic Content Flow Team
 * @version 2.0.0
 * @since 2025-06-17
 */

import { 
  LLMAPIConfig, 
  LLMRequest, 
  LLMResponse, 
  GenerationType 
} from '../../generatortypes';
import { LLMProviderInterface } from '../factory/LLMProviderFactory';
import { extractCodeFromMarkdown, createLegacyMetadata } from '../utils/providerUtils';

export class ClaudeProvider implements LLMProviderInterface {
  private readonly baseUrl = 'https://api.anthropic.com/v1';

  async generateContent(request: LLMRequest): Promise<LLMResponse> {
    const config = request.config;
    if (!config?.apiKey) {
      throw new Error('Claude API key is required');
    }

    const model = config.model || 'claude-3-sonnet-20240229';

    const response = await fetch(`${this.baseUrl}/messages`, {
      method: 'POST',
      headers: {
        'x-api-key': config.apiKey,
        'Content-Type': 'application/json',
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model,
        max_tokens: config.maxTokens || 2048,
        temperature: config.temperature || 0.3,
        system: this.getSystemPrompt(request.type),
        messages: [
          {
            role: 'user',
            content: request.prompt
          }
        ]
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Claude API error: ${response.status} ${error}`);
    }

    const data = await response.json();
    const content = data.content?.[0]?.text || '';
    
    if (!content) {
      throw new Error('No content generated by Claude');
    }

    // Extract code from markdown if present (legacy compatibility)
    const extractedContent = extractCodeFromMarkdown(content);
    const legacyMetadata = createLegacyMetadata('Anthropic Claude');

    return {
      content: extractedContent,
      provider: 'claude',
      model,
      confidence: this.calculateConfidence(data),
      usage: {
        promptTokens: data.usage?.input_tokens || 0,
        completionTokens: data.usage?.output_tokens || 0,
        totalTokens: (data.usage?.input_tokens || 0) + (data.usage?.output_tokens || 0)
      },
      timestamp: new Date().toISOString(),
      metadata: {
        stopReason: data.stop_reason,
        stopSequence: data.stop_sequence,
        messageId: data.id,
        // Legacy compatibility fields
        ...legacyMetadata
      }
    };
  }

  async testConnection(config: LLMAPIConfig): Promise<{ success: boolean; error?: string }> {
    if (!config.apiKey) {
      return { success: false, error: 'API key is required' };
    }

    try {
      // Claude doesn't have a simple ping endpoint, so we make a minimal request
      const response = await fetch(`${this.baseUrl}/messages`, {
        method: 'POST',
        headers: {
          'x-api-key': config.apiKey,
          'Content-Type': 'application/json',
          'anthropic-version': '2023-06-01'
        },
        body: JSON.stringify({
          model: 'claude-3-haiku-20240307',
          max_tokens: 10,
          messages: [{ role: 'user', content: 'test' }]
        }),
      });

      if (response.ok || response.status === 400) { // 400 might be rate limit but key is valid
        return { success: true };
      } else {
        const error = await response.text();
        return { success: false, error: `HTTP ${response.status}: ${error}` };
      }
    } catch (error) {
      return { success: false, error: error instanceof Error ? error.message : 'Connection failed' };
    }
  }

  getProviderInfo() {
    return {
      name: 'Anthropic Claude',
      models: ['claude-3-opus-20240229', 'claude-3-sonnet-20240229', 'claude-3-haiku-20240307'],
      defaultModel: 'claude-3-sonnet-20240229'
    };
  }

  getUsageEstimate(request: LLMRequest): { estimatedTokens: number; estimatedCost: number } {
    const estimatedTokens = Math.ceil(request.prompt.length / 4) + 500;
    const costPerToken = 0.000003; // Rough estimate for Claude 3 Sonnet
    return { estimatedTokens, estimatedCost: estimatedTokens * costPerToken };
  }

  private getSystemPrompt(type: GenerationType): string {
    const basePrompt = 'You are an expert code generator for the Agentic Content Flow system.';
    
    switch (type) {
      case 'process':
        return `${basePrompt} Generate JavaScript process functions that are secure, efficient, and well-documented.`;
      case 'flow':
        return `${basePrompt} Generate complete flow structures with nodes and edges that create meaningful data processing pipelines.`;
      default:
        return basePrompt;
    }
  }

  private calculateConfidence(data: any): number {
    // Calculate confidence based on stop reason
    if (data.stop_reason === 'end_turn') return 0.85;
    if (data.stop_reason === 'max_tokens') return 0.7;
    return 0.5;
  }
}