/**
 * Ollama Provider
 * 
 * Ollama local LLM API implementation for content generation.
 * Supports local models like Llama 2, Code Llama, Mistral, etc.
 * 
 * @author Agentic Content Flow Team
 * @version 2.0.0
 * @since 2025-06-17
 */

import { 
  LLMAPIConfig, 
  LLMRequest, 
  LLMResponse, 
  GenerationType 
} from '../../generatortypes';
import { LLMProviderInterface } from '../factory/LLMProviderFactory';
import { extractCodeFromMarkdown, createLegacyMetadata } from '../utils/providerUtils';

export class OllamaProvider implements LLMProviderInterface {
  private readonly defaultBaseUrl = 'http://localhost:11434';

  async generateContent(request: LLMRequest): Promise<LLMResponse> {
    const config = request.config;
    const model = config?.model || 'gemma2:2b';
    const baseUrl = config?.baseUrl || this.defaultBaseUrl;

    const response = await fetch(`${baseUrl}/api/generate`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model,
        prompt: `${this.getSystemPrompt(request.type)}\n\n${request.prompt}`,
        stream: false,
        options: {
          temperature: config?.temperature || 0.3,
          num_predict: config?.maxTokens || 2048,
        }
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Ollama API error: ${response.status} ${error}`);
    }

    const data = await response.json();
    const content = data.response || '';
    
    if (!content) {
      throw new Error('No content generated by Ollama');
    }

    // Extract code from markdown if present (legacy compatibility)
    const extractedContent = extractCodeFromMarkdown(content);
    const legacyMetadata = createLegacyMetadata('Ollama local LLM');
    // Add Ollama-specific suggestion
    legacyMetadata.suggestions.push('Ollama runs locally for privacy');

    return {
      content: extractedContent,
      provider: 'ollama',
      model,
      confidence: this.calculateConfidence(data),
      usage: {
        promptTokens: data.prompt_eval_count || 0,
        completionTokens: data.eval_count || 0,
        totalTokens: (data.prompt_eval_count || 0) + (data.eval_count || 0)
      },
      timestamp: new Date().toISOString(),
      metadata: {
        totalDuration: data.total_duration,
        loadDuration: data.load_duration,
        promptEvalDuration: data.prompt_eval_duration,
        evalDuration: data.eval_duration,
        context: data.context,
        // Legacy compatibility fields
        ...legacyMetadata
      }
    };
  }

  async testConnection(config: LLMAPIConfig): Promise<{ success: boolean; error?: string }> {
    const baseUrl = config?.baseUrl || this.defaultBaseUrl;
    
    try {
      // Test if Ollama is running by checking the tags endpoint
      const response = await fetch(`${baseUrl}/api/tags`);

      if (response.ok) {
        const data = await response.json();
        if (data.models && Array.isArray(data.models)) {
          return { success: true };
        } else {
          return { success: false, error: 'Ollama is running but no models are available' };
        }
      } else {
        const error = await response.text();
        return { success: false, error: `HTTP ${response.status}: ${error}` };
      }
    } catch (error) {
      return { 
        success: false, 
        error: `Cannot connect to Ollama at ${baseUrl}. Make sure Ollama is running locally.`
      };
    }
  }

  getProviderInfo() {
    return {
      name: 'Ollama (Local)',
      models: ['gemma2:2b', 'llama3.2:1b', 'llama3.2:3b', 'codellama:7b', 'codellama:13b', 'mistral:7b', 'phi3:mini', 'qwen2.5:7b'],
      defaultModel: 'gemma2:2b'
    };
  }

  getUsageEstimate(request: LLMRequest): { estimatedTokens: number; estimatedCost: number } {
    const estimatedTokens = Math.ceil(request.prompt.length / 4) + 500;
    return { estimatedTokens, estimatedCost: 0 }; // Local models are free
  }

  private getSystemPrompt(type: GenerationType): string {
    const basePrompt = 'You are an expert code generator for the Agentic Content Flow system.';
    
    switch (type) {
      case 'process':
        return `${basePrompt} Generate JavaScript process functions that are secure, efficient, and well-documented.`;
      case 'flow':
        return `${basePrompt} Generate complete flow structures with nodes and edges that create meaningful data processing pipelines.`;
      default:
        return basePrompt;
    }
  }

  private calculateConfidence(data: any): number {
    // Local models generally have good consistency
    if (data.done === true) return 0.75;
    return 0.5;
  }
}