/**
 * OpenAI Provider
 * 
 * OpenAI GPT API implementation for LLM content generation.
 * Supports GPT-4, GPT-4 Turbo, and GPT-3.5 models.
 * 
 * @author Agentic Content Flow Team
 * @version 2.0.0
 * @since 2025-06-17
 */

import { 
  LLMAPIConfig, 
  LLMRequest, 
  LLMResponse, 
  GenerationType 
} from '../../generatortypes';
import { LLMProviderInterface } from '../factory/LLMProviderFactory';
import { extractCodeFromMarkdown, createLegacyMetadata } from '../utils/providerUtils';

export class OpenAIProvider implements LLMProviderInterface {
  private readonly baseUrl = 'https://api.openai.com/v1';

  async generateContent(request: LLMRequest): Promise<LLMResponse> {
    const config = request.config;
    if (!config?.apiKey) {
      throw new Error('OpenAI API key is required');
    }

    const response = await fetch(`${this.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${config.apiKey}`
      },
      body: JSON.stringify({
        model: config.model || 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: this.getSystemPrompt(request.type)
          },
          {
            role: 'user',
            content: request.prompt
          }
        ],
        temperature: config.temperature || 0.3,
        max_tokens: config.maxTokens || 2048,
        stream: false
      })
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ error: { message: 'Unknown error' } }));
      throw new Error(`OpenAI API error: ${error.error?.message || response.statusText}`);
    }

    const data = await response.json();
    const choice = data.choices?.[0];
    
    if (!choice?.message?.content) {
      throw new Error('No content generated by OpenAI');
    }

    // Extract code from markdown if present (legacy compatibility)
    const extractedContent = extractCodeFromMarkdown(choice.message.content);
    const legacyMetadata = createLegacyMetadata('OpenAI GPT');

    return {
      content: extractedContent,
      provider: 'openai',
      model: data.model || config.model || 'gpt-4o-mini',
      confidence: this.calculateConfidence(choice),
      usage: {
        promptTokens: data.usage?.prompt_tokens || 0,
        completionTokens: data.usage?.completion_tokens || 0,
        totalTokens: data.usage?.total_tokens || 0
      },
      timestamp: new Date().toISOString(),
      metadata: {
        finishReason: choice.finish_reason,
        systemFingerprint: data.system_fingerprint,
        // Legacy compatibility fields
        ...legacyMetadata
      }
    };
  }

  async testConnection(config: LLMAPIConfig): Promise<{ success: boolean; error?: string }> {
    if (!config.apiKey) {
      return { success: false, error: 'API key is required' };
    }

    try {
      const response = await fetch(`${this.baseUrl}/models`, {
        headers: {
          'Authorization': `Bearer ${config.apiKey}`,
        },
      });

      if (response.ok) {
        return { success: true };
      } else {
        const error = await response.text();
        return { success: false, error: `HTTP ${response.status}: ${error}` };
      }
    } catch (error) {
      return { success: false, error: error instanceof Error ? error.message : 'Connection failed' };
    }
  }

  getProviderInfo() {
    return {
      name: 'OpenAI',
      models: ['gpt-4o-mini', 'gpt-4o', 'gpt-4', 'gpt-4-turbo', 'gpt-3.5-turbo'],
      defaultModel: 'gpt-4o-mini'
    };
  }

  getUsageEstimate(request: LLMRequest): { estimatedTokens: number; estimatedCost: number } {
    const estimatedTokens = Math.ceil(request.prompt.length / 4) + 500;
    const costPerToken = 0.00001; // Rough estimate for GPT-4o-mini
    return { estimatedTokens, estimatedCost: estimatedTokens * costPerToken };
  }

  private getSystemPrompt(type: GenerationType): string {
    const basePrompt = 'You are an expert code generator for the Agentic Content Flow system.';
    
    switch (type) {
      case 'process':
        return `${basePrompt} Generate JavaScript process functions that are secure, efficient, and well-documented.`;
      case 'flow':
        return `${basePrompt} Generate complete flow structures with nodes and edges that create meaningful data processing pipelines.`;
      default:
        return basePrompt;
    }
  }

  private calculateConfidence(choice: any): number {
    // Calculate confidence based on finish reason and other factors
    if (choice.finish_reason === 'stop') return 0.9;
    if (choice.finish_reason === 'length') return 0.7;
    return 0.5;
  }
}